<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Welcome - HOME</title>
</head>
<body>
	<h2>Welcome Home - Generate PDF</h2>
	
	<p>
		Click On the below links to generate pdf. The PDF's will be generated by the help of Jasper Reports
	</p>
	
	<br>
	<a href="/pdf-generation/pdf">Download pdf</a>
	
	<br>
	<a href="/pdf-generation/viewpdf" target="_blank">View PDF</a>
</body>
</html>